services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-alpine3.21
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'filmes_top', '-U', 'filmes_top']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env
