[project]
name = "filmes-top-api"
version = "1.0.0"
description = "Api FilmesTop.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
]
