"""add genre field

Revision ID: 0267369c2c1a
Revises: dfdf4bdc6b1d
Create Date: 2025-05-19 02:50:04.182901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0267369c2c1a'
down_revision = 'dfdf4bdc6b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
