"""add movie informations

Revision ID: 3f28b9b383be
Revises: 46b1981e614d
Create Date: 2025-05-18 15:10:48.198349
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f28b9b383be'
down_revision = '46b1981e614d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False)
        )
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False)
        )
        batch_op.add_column(
            sa.Column('description', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('duration_minutes', sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('description')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
