"""add rental relationships

Revision ID: 9268dead5ab5
Revises: 0267369c2c1a
Create Date: 2025-05-19 03:05:03.926482
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9268dead5ab5'
down_revision = '0267369c2c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rentals',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('movie_id', sa.String(), nullable=False),
        sa.Column('rented_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movies.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
