"""add review counts to movie

Revision ID: a7c0db0c376b
Revises: 9ab488e1c077
Create Date: 2025-05-19 11:13:45.394252
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c0db0c376b'
down_revision = '9ab488e1c077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('total_reviews', sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column('average_rating', sa.Float(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('average_rating')
        batch_op.drop_column('total_reviews')

    # ### end Alembic commands ###
